name: indivara_boilerplate
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.5
  package_info_plus: ^3.1.2
  responsive_sizer: ^3.1.1
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  flutter_svg: ^2.0.7
  dartz: ^0.10.1
  intl: ^0.18.0
  dio: ^5.3.2
  get: ^4.6.5

  # HTTP INSPECTOR
  alice_lightweight: ^3.4.0
  fimber: ^0.6.6
  shake: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.3.3

# CHANGE APP ICON (flutter pub run flutter_launcher_icons)
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher/ic_launcher.png"

# ASSETS GENERATOR RUN (flutter packages pub run build_runner build)
flutter_gen:
  output: lib/ui_kit/generated_theme/
  assets:
    package_parameter_enabled: false
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/jpg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/font/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/font/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/font/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/font/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/font/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/font/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/font/montserrat/Montserrat-Thin.ttf
          weight: 100

